apiVersion: apps/v1
kind: Deployment
metadata: 
  name: to-do-app-deployment
spec:
  selector:
    matchLabels:
      app: to-do-app
  replicas: 2
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: keerthana2910/to-do-app:latest
          ports: 
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 3.7.0.0/16
  selector:
      app: to-do-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
